project:
  type: book

book:
  title: "Remotely sensing cities and environments: learning diary"
  author: "Hannah Schuller"
  date: "2/6/2024"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: united
  pdf:
    documentclass: scrreprt

editor: visual

