project:
  type: book
  output-dir: docs

book:
  title: "Remotely Sensing Cities and Environments: Learning Diary"
  author: "Hannah Schuller"
  date: "2/6/2024"
  chapters:
    - index.qmd
    - week1.qmd
    - week2.qmd
    - week3.qmd
    - week4.qmd
    - week5.qmd
    - week6.qmd

format:
  html:
    theme: united
  pdf:
    documentclass: scrreprt

editor: visual

