# Personal introduction {.unnumbered}

Hello! My name's Hannah and this is my Quarto learning diary for CASA0023.

For a bit of background on me; I'm currently enrolled on the Social and Geographic Data Science MSc programme at UCL, but come from a background in Physical Geography after graduating from the University of Edinburgh in 2023. I was first introduced to remote sensing during my undergrad which saw many projects focus on remotely sensing forests and green spaces across Scotland. After a gentle introduction to different sensors, programs and earth-focused applications in the first couple years, I sought more opportunities to combine my primary research interest, the cryosphere, with remote sensing. Fortunately for me the two go increasingly hand-in-hand and as a result my final two years in Edinburgh were focused almost entirely on remote sensing of cold places. My dissertation saw me map ice algal blooms across the Greenland Ice Sheet using Sentinel-3 imagery and this remains my magnum opus (I joke - the maps I made were extremely basic and honestly quite ugly).

I've also worked for two companies as a remote sensing intern/geospatial analyst which taught me a great deal; the first was Space Intelligence in Edinburgh and the other was CF Partners in London. At Space Intelligence I worked on a land cover classification project the company had been awarded by the Tanzanian government looking to monitor deforestation, whilst at CF I was thrown in the deep end with SAR interferometry and Google Earth Engine to produce a forestry-related machine learning model. Before this point, almost all of my interactions with remotely sensed data had been during solo projects for uni, so it was cool to see what working in a team was like during these professional experiences. I found myself learning a *lot* in a very short amount of time and I was actually quite sad when the time came to leave both companies.

This jumble of academic and professional experiences has exposed me to quite a range of data products (Sentinel-1,2,3, Landsat, WorldView, MODIS etc.) and applications (ENVI, GEE, Arc+QGIS, SNAP etc.), not to mention the associated headaches and frustrations that come with working in the field. These headaches seem not to have put me off though as I selected this course keen not just to learn more about specific remote sensing techniques, but also to think about their applications in urban contexts. My undergrad was very quantitative and environment-focused which left me often looking down on anything even vaguely 'human' or development based. I'd like to challenge that naive perception throughout this course and learn more about how the techniques I'm already familiar with can be used to support cities and the people who live in them.

I hope you enjoy reading my learning diary!
